### ISSUE TITLE
Data cleaning in addition to loading

### ISSUE THREAD

**Issue by james-large** [time-series-machine-learning/tsml-java#114]
Following talks on Tuesday and today, I reckon a decent addition for both public AND research usability would be to have default, bog-standard, non-controversial and unintelligent weka Filters or new 'Transformers' or whatever for data cleaning (of timeseries data in particular). 

These can then optionally applied to data when loading it in via whatever means (or always 'applied', and for stuff like standardised UCR data nothing happens). Main ideas from my POV for these would be:

- Remove identical instances
- Remove instances with missing classes
- Perform basic missing value imputation 
- Perform any basic padding or truncating to get to equal length
- Maybe more?

- Provide a summary of changes made 

Such that from a public usability point of view, people with their fresh imperfect dataset can easily just get numbers from our algs that aren't engineered to handle difficult factors at the moment. And from a research point of view, when adding datasets to UCR TSC or UEA MTSC, we can potentially leave datasets in an imperfect form similar to the option to leave datasets unnormalised. But, we also provide the bog standard difficult to argue with way of getting it into a complete standard form for easy comparison between classifiers. For particular applications, people more involved/interested can define settings for/write their own data cleaning processes etc.

This can also be applied to sktime, and as an addition to all this, we should probably add support for other file types, namely .ts files but also simple csv files with not meta/attribute information. Maybe this should all be done after the/a dedicated timeseries instance type is drafted up. **On a side note, this could probably make for a decent third year project too**

**Comment by mloning** [comment]
As sktime compatible transformers?

**Comment by James-Large** [comment]
Compatible as in with same API's across the two languages, or as in implemented as a Transformer specifically in the sktime version? Well both I guess actually, there was talk of replicating Transformers in the java version to replace/augment/perhaps wrap weka Filters, but whether that's a short or long term goal remains to be seen

**Comment by TonyBagnall** [comment]
so yes I think we move to Transformers extending Filter for compatibility, not least for sanity when switching. I was pretty sure I had implemented padding and truncation years ago, but its not in the filters.  
![image](https://user-images.githubusercontent.com/9594042/61910326-3be81c80-af2c-11e9-87d6-dbd914f19199.png)

**Comment by TonyBagnall** [comment]
Weka has a fair few built in. There is a decent chunk of boring work to convert, we need an undergrad :) But we first need to decide on the Transformer interface. 

abstract class Transformer extends BatchFilter{
   void buildTransformer(Instances) with a default to do nothing for unsupervised transforms
   Instance transform(Instance)
   Instances transform(Instances)   
}

we will still need all the determineOutputFormat from Filters, but can inherit all that.
