### ISSUE TITLE
STC throws error generating train files for rare classes

### ISSUE THREAD

**Issue by Deepoli** [time-series-machine-learning/tsml-java#360]
STC throws the attached exception when generating train files when the arff has a class imbalance and contains rare classes. I think it is caused by one of the resamples having none of one of the classes in one of the folds.
[Fold9.txt](https://github.com/uea-machine-learning/tsml/files/4643337/Fold9.txt)

**Comment by TonyBagnall** [comment]
I can confirm shapelets transform fails poorly when there are no shapelets, it should throw a meaningful exception
