### ISSUE TITLE
RISE throwing ClassNotFoundException

### ISSUE THREAD

**Issue by Deepoli** [time-series-machine-learning/tsml-java#366]
Occurs when generating train files for data when the arff has a class imbalance and contains rare classes.
[Fold1.txt](https://github.com/uea-machine-learning/tsml/files/4655710/Fold1.txt)

**Comment by MJFlynn** [comment]
Hi @Deepoli,
Would it be possible to share the dataset you were using please?
Also, if possible could you share the parameters used too.
I'll try and recreate the issue locally.

**Comment by Deepoli** [comment]
Hi, I have pm'd you the data. Default parameters used with no contract time. Generate train files set to true. 30 folds.

**Comment by Deepoli** [comment]
Running on the latest Dev Branch.
