### ISSUE TITLE
Add a DimensionIndependentTransformer for multivariate data

### ISSUE THREAD

**Issue by TonyBagnall** [time-series-machine-learning/tsml-java#390]
it would be good to have a wrapper that could use any Transformer capable of univariate transform and apply it independently on each dimension, returning a new multivariate dataset, in a way similar to DimensionIndependentEnsemble

**Comment by Multivin12** [comment]
I will have ago at resolving this issue :)

**Comment by TonyBagnall** [comment]
base model from https://github.com/uea-machine-learning/tsml/pull/394, it cannot handle TrainableTransformers yet though, so I'll leave this open
