### ISSUE TITLE
Multidimensional splitter

### ISSUE THREAD

**Issue by TonyBagnall** [time-series-machine-learning/tsml-java#411]
there is a problem with the multivariate resampler we think. Currently on mattDev:

doing this
![image](https://user-images.githubusercontent.com/9594042/89044369-c6ced480-d341-11ea-9bd8-6a3d9494d66a.png)

gives this
![image](https://user-images.githubusercontent.com/9594042/89044425-dbab6800-d341-11ea-9a09-2a2dd760682b.png)

happens on all but the default fold

**Comment by TonyBagnall** [comment]
bug seems to be in loading the data. DatasetLoading line 233 calls the new resampler 
![image](https://user-images.githubusercontent.com/9594042/89045324-3f826080-d343-11ea-9a89-7324240746eb.png)

**Comment by ABostrom** [comment]
I think this all stems from when i sped up the resample, and fundamentally the deep shallow copy problem seems to have remained. Although I could have sworn i tested this and it was fine.
