### ISSUE TITLE
Transformers breaking when using Instances

### ISSUE THREAD

**Issue by MatthewMiddlehurst** [time-series-machine-learning/tsml-java#431]
A number of transformers i have tested using transform(Instances)/transform(Instance) throw exceptions.
Ones currently broken include: ARMA, MatrixProfile, Differences, PowerSpectrum and SAX.

Aaron has tested the TimeSeriesInstances transform methods for these and verified that they work, but for backwards compatibility reasons both methods are required to work.

If both transform(Instances) and transform(TimeSeriesInstances) do the same thing it may just be easier to turn Instances into TimeSeriesInstances by default for an easy fix? May be a bit inefficient though.

**Comment by TonyBagnall** [comment]
has this been fixed @MatthewMiddlehurst ?
