### ISSUE TITLE
Libraries

### ISSUE THREAD

**Issue by goastler** [time-series-machine-learning/tsml-java#447]
This issue is a rolling record of what libraries are currently in use and their purpose.

Please leave a comment of the library name, purpose / usage and whether it's a jar or gradle based library.

We can discuss whether libraries should be kept / removed here and get rid of the duplicate gradle / jar entries.

**Comment by goastler** [comment]
junit v4 via gradle, used for unit testing

**Comment by goastler** [comment]
guava via gradle, used in my code afaik and can be removed as I only use it a handful of times

**Comment by goastler** [comment]
apache commons v4 via gradle, purpose unknown

**Comment by goastler** [comment]
apache commons math v3 via gradle, I _believe_ this is to do with fft in rise @MJFlynn ?

**Comment by goastler** [comment]
hppc correctsearch via gradle, is this for boss @MatthewMiddlehurst ?

**Comment by goastler** [comment]
jcommander via gradle, used for cmdline params in experiments

**Comment by goastler** [comment]
jexcelapi via gradle, used for spreadsheets right @James-Large ?

**Comment by goastler** [comment]
kyro via gradle, I _believe_ this is for xgboost

**Comment by goastler** [comment]
matlab-control via gradle, used for diagrams output during results evaluation

**Comment by goastler** [comment]
sizeOf via gradle, used for evaluating size of an obj in memory. @MatthewMiddlehurst do you still use this? I don't anymore

**Comment by goastler** [comment]
xgboost4j via gradle, provides xgboost implementation

**Comment by goastler** [comment]
guava-testlib via gradle, provides forced garbage collection afaik and nothing else. Potentially get rid of this

**Comment by goastler** [comment]
gson via gradle, don't think anyone uses this anymore. Handles JSON input/output

**Comment by goastler** [comment]
duplicate jars / gradle libraries:
- commons collections
- commons math3
- guava
- guava testlib
- hppc
- jcommander
- junit
- kyro
- matlab control
- xgboost4j

**Comment by goastler** [comment]
commons io via jar, not sure what this is used for

**Comment by goastler** [comment]
jtransforms via jar, not sure what this is used for

**Comment by goastler** [comment]
liblinear via jar, not sure what this is used for

**Comment by goastler** [comment]
commons logging via jar, not sure what this is used for

**Comment by goastler** [comment]
PF and TS-CHIEF wrapped via jar

**Comment by goastler** [comment]
*Two* versions of xgboost via jar, iirc one is for windows and one is for linux / the cluster

**Comment by MatthewMiddlehurst** [comment]
> 
> 
> hppc correctsearch via gradle, is this for boss @MatthewMiddlehurst ?

Used in WEASEL

> 
> 
> sizeOf via gradle, used for evaluating size of an obj in memory. @MatthewMiddlehurst do you still use this? I don't anymore

I dont use this anymore either

> 
> 
> liblinear via jar, not sure what this is used for

Required for WEASEL also, useful to keep. Also going to include libsvm which is similar.

> 
> 
> PF and TS-CHIEF wrapped via jar

Can probably get rid of PF now? #435 needs to be done before removing TS-CHIEF

**Comment by MatthewMiddlehurst** [comment]
From PR #438 and our previous Friday meeting, we are looking to add DL4J/ND4J which has 3 imports recommended from https://deeplearning4j.konduit.ai/getting-started/quickstart.

These are:

// https://mvnrepository.com/artifact/org.deeplearning4j/deeplearning4j-core
    compile group: 'org.deeplearning4j', name: 'deeplearning4j-core', version: '1.0.0-beta4'
    // https://mvnrepository.com/artifact/org.nd4j/nd4j-native-platform
    compile group: 'org.nd4j', name: 'nd4j-native-platform', version: '1.0.0-beta4'
    // https://mvnrepository.com/artifact/org.datavec/datavec-api
    compile group: 'org.datavec', name: 'datavec-api', version: '1.0.0-beta4'

I chose beta4 as it was the last version to include a setNumThreads function instead of using enviroment variables. For ND4J, native uses a CPU backend and platform includes binaraies for most major OS.
