### ISSUE TITLE
DatasetLoading sample methods

### ISSUE THREAD

**Issue by TonyBagnall** [time-series-machine-learning/tsml-java#501]
the DatasetLoading methods sampleX seem to fail 
![image](https://user-images.githubusercontent.com/9594042/112137550-4d357080-8bc8-11eb-9ce7-6f76d5c52814.png)

**Comment by TonyBagnall** [comment]
they also call a depreciated method for multivariate 
![image](https://user-images.githubusercontent.com/9594042/112137893-bd43f680-8bc8-11eb-8ade-d18cda3c6319.png)

**Comment by James-Large** [comment]
Seems fine for me, code snippet? 

![image](https://user-images.githubusercontent.com/44509982/112139552-cc2ba880-8bca-11eb-98fb-6a1577f5664c.png)


And afaik that's the most up to date mv resampling function for weka instances. Iirc, the one being used is correct and the one without _old was funky/broken in some way. There's the tsinstances resampler of course but that'll wait for the wholesale overhaul

**Comment by TonyBagnall** [comment]
Instances[] gp = DatasetLoading.sampleGunPoint(0);

file path problem maybe, too long? 
![image](https://user-images.githubusercontent.com/9594042/112143285-95a45c80-8bcf-11eb-8ffe-b59cc21c5f0a.png)

**Comment by James-Large** [comment]
True maybe, 256 char limit iirc on windows. Shouldn't be any permission problems with that location, right?

**Comment by TonyBagnall** [comment]
hmm, not the string lengths, this works. Seems to be looking for GunPoint.arff not GunPoint_TRAIN.arff? 
![image](https://user-images.githubusercontent.com/9594042/112155380-29305a00-8bdd-11eb-88e6-714efbb23361.png)

**Comment by James-Large** [comment]
It goes through the cases describe in the jdoc attached to sampledataset, including _TRAIN/TEST, think you're gonna have to just go through with the debugger and see exactly what it's trying to load etc, can't do it this end since I don't get the error

**Comment by TonyBagnall** [comment]
its not high priority, I was just trying to do something easy for ML coursework, its probably one drive, its fecking with me today
