### ISSUE TITLE
To make HIVE-COTE classifier adapt TimeSeriesInstances

### ISSUE THREAD

**Issue by divbuildsdivs** [time-series-machine-learning/tsml-java#529]

**Comment by TonyBagnall** [comment]
good idea, @MatthewMiddlehurst any thoughts?

**Comment by TonyBagnall** [comment]
So just looking at HIVE_COTE, and it is indeed not set up for TimeSeriesInstances. This would be a good thing to work on.

For this issue, I suggest just overload build and predict methods to take TimeSeriesInstances, check capabilities, convert to Instances and call Instances method
