### ISSUE TITLE
then what should be used or tsml-py or sktime?

### ISSUE THREAD

**Issue by Sandy4321** [time-series-machine-learning/tsml-java#544]
it is written 
UEA Time Series Classification
https://travis-ci.com/uea-machine-learning/tsml.svg?branch=master
A [Weka](https://svn.cms.waikato.ac.nz/svn/weka/branches/stable-3-8/)-compatible Java toolbox for time series classification, clustering and transformation. For the python sklearn-compatible version, see [sktime](https://github.com/alan-turing-institute/sktime)

but there is python repo
https://github.com/time-series-machine-learning/tsml-py

then what should be used or tsml-py or sktime?

**Comment by MatthewMiddlehurst** [comment]
Hello, we are no longer affiliated with sktime, and tsml-py is mostly just my area for developing algorithms 🙂. 

If you require a Python package for time series, I suggest [aeon](https://github.com/aeon-toolkit/aeon), where we currently implement and maintain all of our stuff. You are welcome to use and create issues for tsml-py it if it has algorithms you need, but aeon will be much more feature rich and well documented currently.

I didn't realise the readme here was out of date, thanks for bringing that to our attention. We don't really dev here anymore so no one noticed!
